apiVersion: v1
kind: Service
metadata:
  name: {{ include "tcp-single.fullname" . }}
  labels:
    {{- include "tcp-single.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.port.exposePort }}
      targetPort: {{ .Values.port.targetPort }}
      protocol: {{ .Values.port.protocol }}
      name: {{ .Values.port.name }}
  selector:
    app: {{ .Values.appLabel }}
