trigger:
- master

resources:
- repo: self

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ci/build-and-push.yml
      parameters:
        problems:
          - name: 'problem1'
            path: 'problem1/Dockerfile'
          - name: 'problem2'
            path: 'problem2/Dockerfile'

