trigger:
- master

resources:
- repo: self

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: ci/build-and-push.yml
      parameters:
        problems:
          - 'problem1'
          - 'problem2'
          - 'statics'

